### ISSUE TITLE
Ansible issue downloading role via Ansible 1.7.x

### ISSUE THREAD

**Issue by mattee6** [geerlingguy/temperature-monitor#26]
I keep getting the following error:

```
 downloading role 'git', owned by geerlingguy
 no version specified, installing 1.2.1
 - downloading role from https://github.com/geerlingguy/ansible-role-git/archive/1.2.1.tar.gz
 - extracting geerlingguy.git to /etc/ansible/roles/geerlingguy.git
geerlingguy.git was installed successfully
 downloading role 'mysql', owned by geerlingguy
https://galaxy.ansible.com/roles/435/versions/?page=2&page_size=50
Traceback (most recent call last):
  File "/usr/bin/ansible-galaxy", line 822, in <module>
    main()
  File "/usr/bin/ansible-galaxy", line 816, in main
    fn(args, options, parser)
  File "/usr/bin/ansible-galaxy", line 695, in execute_install
    if len(role_versions) > 0:
TypeError: object of type 'NoneType' has no len()
```

**Comment by mattee6** [comment]
I am using ansible 1.7.2
I installed from apt-get.

This installation has issues, current version is 2.2.1

To solve:

I removed apt-get package and installed via pip.  

And installed pip install markupsafe (as per https://github.com/rdickert/project-quicksilver/issues/6), now have version 2.2.1.0

**Comment by geerlingguy** [comment]
Great! Glad you could get it solved—I imagine with the current version things are working properly now, so I'll go ahead and close out this issue. Related problem: #27
