### ISSUE TITLE
Update for Raspbian 10 / Debian 10

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/temperature-monitor#35]
Currently this project's Vagrant setup runs on an old now-unsupported version of Debian 8. Debian 10 is the base for Raspbian 10, so I would like to make sure everything runs on that OS version instead.

**Comment by geerlingguy** [comment]
Also need to upgrade Node.js from 0.12 to 12.x :O

**Comment by geerlingguy** [comment]
The Node.js dashboard app is giving:

```
(node:13813) [DEP0095] DeprecationWarning: timers.enroll() is deprecated. Please use setTimeout instead.
(node:13813) [DEP0126] DeprecationWarning: timers.active() is deprecated. Please use timeout.refresh() instead.
/vagrant/dashboard/node_modules/mysql/lib/protocol/Parser.js:82
        throw err;
        ^

Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MariaDB client
    at Handshake.Sequence._packetToError (/vagrant/dashboard/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)
    at Handshake.ErrorPacket (/vagrant/dashboard/node_modules/mysql/lib/protocol/sequences/Handshake.js:101:18)
    at Protocol._parsePacket (/vagrant/dashboard/node_modules/mysql/lib/protocol/Protocol.js:271:23)
    at Parser.write (/vagrant/dashboard/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/vagrant/dashboard/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/vagrant/dashboard/node_modules/mysql/lib/Connection.js:82:28)
    at Socket.emit (events.js:311:20)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    --------------------
    at Protocol._enqueue (/vagrant/dashboard/node_modules/mysql/lib/protocol/Protocol.js:135:48)
    at Protocol.handshake (/vagrant/dashboard/node_modules/mysql/lib/protocol/Protocol.js:52:41)
    at PoolConnection.connect (/vagrant/dashboard/node_modules/mysql/lib/Connection.js:109:18)
    at Pool.getConnection (/vagrant/dashboard/node_modules/mysql/lib/Pool.js:45:23)
    at /vagrant/dashboard/router/routes/temps.js:73:18
    at fn (/vagrant/dashboard/node_modules/async/lib/async.js:641:34)
    at Immediate.<anonymous> (/vagrant/dashboard/node_modules/async/lib/async.js:557:34)
    at processImmediate (internal/timers.js:456:21) {
  code: 'ER_NOT_SUPPORTED_AUTH_MODE',
  errno: 1251,
  sqlState: '08004',
  fatal: true
}
error: Forever detected script exited with code: 1
error: Script restart attempt #1
(node:14474) [DEP0095] DeprecationWarning: timers.enroll() is deprecated. Please use setTimeout instead.
(node:14474) [DEP0126] DeprecationWarning: timers.active() is deprecated. Please use timeout.refresh() instead.
/vagrant/dashboard/node_modules/mysql/lib/protocol/Parser.js:82
        throw err;
        ^

Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MariaDB client
    at Handshake.Sequence._packetToError (/vagrant/dashboard/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)
    at Handshake.ErrorPacket (/vagrant/dashboard/node_modules/mysql/lib/protocol/sequences/Handshake.js:101:18)
    at Protocol._parsePacket (/vagrant/dashboard/node_modules/mysql/lib/protocol/Protocol.js:271:23)
    at Parser.write (/vagrant/dashboard/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/vagrant/dashboard/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/vagrant/dashboard/node_modules/mysql/lib/Connection.js:82:28)
    at Socket.emit (events.js:311:20)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    --------------------
    at Protocol._enqueue (/vagrant/dashboard/node_modules/mysql/lib/protocol/Protocol.js:135:48)
    at Protocol.handshake (/vagrant/dashboard/node_modules/mysql/lib/protocol/Protocol.js:52:41)
    at PoolConnection.connect (/vagrant/dashboard/node_modules/mysql/lib/Connection.js:109:18)
    at Pool.getConnection (/vagrant/dashboard/node_modules/mysql/lib/Pool.js:45:23)
    at /vagrant/dashboard/router/routes/temps.js:73:18
    at fn (/vagrant/dashboard/node_modules/async/lib/async.js:641:34)
    at Immediate.<anonymous> (/vagrant/dashboard/node_modules/async/lib/async.js:557:34)
    at processImmediate (internal/timers.js:456:21) {
  code: 'ER_NOT_SUPPORTED_AUTH_MODE',
  errno: 1251,
  sqlState: '08004',
  fatal: true
}
```

**Comment by geerlingguy** [comment]
Have to upgrade mysql dependency, and switch from jade to pug.

**Comment by geerlingguy** [comment]
Yay, got it all working again!

<img width="1262" alt="Screen Shot 2020-03-05 at 11 51 09 AM" src="https://user-images.githubusercontent.com/481677/76009928-a35d4600-5ed7-11ea-8be6-9415e9b58443.png">

**Comment by ShosMeister** [comment]
Yeah this is old but hey, so am I :) Just found it and looking for something like this - actually the air quality monitor too. Question though as it seems you're running this from a VM - but you don't indicate the specs or anything about that. Do you have a detailed setup doc anywhere?

Thanks!
